import { useState } from "react";

import { ApiError, triageIssue } from "../api.js";
import Button from "./Button.jsx";
import FlowField from "./FlowField.jsx";

const TYPE_LABELS = {
  bug: "Bug",
  feature_request: "Feature request",
  question: "Question",
  task: "Task",
};

const PRIORITY_LABELS = {
  low: "Low",
  medium: "Medium",
  high: "High",
  critical: "Critical",
};

// Rendered with key={issueId} by IssueDetail, so switching issues remounts the
// panel and starts from scratch: triage is never stored.
export default function TriagePanel({ issueId }) {
  const [triage, setTriage] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function runTriage() {
    setLoading(true);
    setError("");

    try {
      setTriage(await triageIssue(issueId));
    } catch (caught) {
      setError(
        caught instanceof ApiError && typeof caught.body?.detail === "string"
          ? caught.body.detail
          : "Triage failed.",
      );
    } finally {
      setLoading(false);
    }
  }

  if (triage) {
    const { result } = triage;

    return (
      <section className="triage triage-result" aria-live="polite">
        <div className="triage-head">
          <h3>AI triage</h3>
          <Button variant="ghost" onClick={runTriage} disabled={loading}>
            {loading ? "Re-running…" : "Re-run"}
          </Button>
        </div>

        <div className="badge-row">
          <span className={`badge badge-type-${result.type}`}>
            {TYPE_LABELS[result.type]}
          </span>
          <span className={`badge badge-priority-${result.priority}`}>
            {PRIORITY_LABELS[result.priority]} priority
          </span>
          <span className="badge badge-component">{result.component}</span>
        </div>

        <dl className="triage-fields">
          <dt>Summary</dt>
          <dd>{result.summary}</dd>
          <dt>Why</dt>
          <dd>{result.rationale}</dd>
          <dt>Suggested next action</dt>
          <dd>{result.suggested_next_action}</dd>
        </dl>

        <p className="triage-foot">
          Advisory only — generated by {triage.model} from the report text alone.
        </p>
      </section>
    );
  }

  return (
    <section className="triage triage-cta">
      <FlowField className="triage-art" />
      <div className="triage-cta-body">
        <h3>AI triage</h3>
        <p>
          Have Claude categorize this report and suggest a next step. Nothing is stored,
          and a human still decides what happens.
        </p>
        {error && <p className="triage-error">{error}</p>}
        <Button onClick={runTriage} disabled={loading}>
          {loading ? "Analyzing…" : "Run AI triage"}
        </Button>
      </div>
    </section>
  );
}
